# Generated by Django 5.2 on 2026-03-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0008_alter_prestamo_prestamo_dias_plazo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaFestivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={"db_table": "dias_festivos",},
        ),
        migrations.AddField(
            model_name="prestamo",
            name="prestamo_entregado_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="prestamo_fecha_entrega_real",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="prestamo_estatus",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente de entrega"),
                    ("Activo", "Activo"),
                    ("Devuelto", "Devuelto"),
                    ("Vencido", "Vencido"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
