# Generated by Django 5.2 on 2026-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0009_diafestivo_prestamo_prestamo_entregado_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="prestamo_estatus",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente de entrega"),
                    ("Activo", "Activo"),
                    ("Devuelto", "Devuelto"),
                    ("Vencido", "Vencido"),
                    ("Cancelado", "Cancelado por usuario"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
