# Generated by Django 5.2 on 2026-03-20 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0010_alter_prestamo_prestamo_estatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="usuario_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("usado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.usuario",
                    ),
                ),
            ],
            options={"db_table": "password_reset_tokens",},
        ),
    ]
