# Generated by Django 5.2 on 2026-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0011_usuario_usuario_email_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usuario_rol",
            field=models.CharField(
                choices=[("alumno", "Alumno"), ("docente", "Docente")],
                default="alumno",
                max_length=20,
            ),
        ),
    ]
